# 1. 구글 클라우드 키 (기존에 쓰던 것, 없다면 채워넣으세요)
[gcp_service_account]
type = "service_account"
project_id = "unicornfinder-486913"
project_id = "gen-lang-client-0982832571"
private_key_id = "1084412fc98e44128fdee2278e816ca88d4dbe12",
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDJElXSxDCNN8cd\nGpe0YqvRS2zRZHVsz3DdOrxsBquRvMXj7FiYCbWHaiw202GGT/VxJdYLnIqgKyLK\nDrfaiyBluClQiaTxH4PGfwqOZWCW5JpEaKGpJb4WQO0AUhikwOIb94Iy8hzaKVwm\nutsBJlUSNtIpnA6VBLuT2hTUr2lRcuNIqCwyeKgDtXrgCMvNKX5Z/V9ifhwEAlh4\n58VhWDQ4sSNuzePA97joq5hZx7Ub/6EeFuleFR9XW/Hn6/0MKSS0mWYBKJFcdBCy\nE8PVJ+97w0MnD8jw9DSKUwcEdzVC4fxiKBsMrx7NXspXJ5X4V3Kdq93h83zf5fDb\n0sCmspGVAgMBAAECggEAHlSBdSpKb5bdFmcLQLbMl6TSvJA0hU4SRpDEWOA1s6Vf\nzWZ6o659Pzi1BC0lDiNUEPYF4FkD8S6okAWh1pm7cJSTyNYGdyfLkx7ZOwsQQ5qm\nqZCF6DOtBYLULUL0/C8rPFA8x84NK5xnDeGMRRNg7D8wOv4TFgfxepdAIqf2EUao\njxT4cV1lE6/Sj0lE0VyDS0Y5kpzg3yVowVwA83XAivf1v87wHDFUO6TQUYHBBSMN\nR4s9EqMglaQd1nk2xsN7DTaN1u05fsvWHUQbovJClTOzjvSQzFDlesktbEBQh/hY\nAow3IQNiam0mUAefULmGHdS7cTEZ3EBcSbWSjRnEGQKBgQDjywTT8/LVftjqy7nL\nnt/o9UTZjrzwTcoacyQkeyUzYj/kO4cbtYmXoZ3Ll+x/WaMJNFf5AVTWVij9s8vh\nmdRxy0s0XKk/uGNAmS2F5MLforBmAQF3JpFMbQloOtbr88lNDZ+jtlZyhsah3beK\nLgfyARr+nnCwJIR4db6MrzlpmQKBgQDh+EETZDLuYyXUKcfcR4BeY8F0Tmyt71oE\n/i0sCDpEWVOSMIh84Od/1JzHQKdLaTac4fG7ChsTqKLvRKOgNXMSsfNHVlrcDBf9\nBHfgVkji7rwUgOOQuiAMg0Y8Rm55jvwYq8A/bBXqTsaYnJsfETYLXYhnUOkydGhM\noF/F+DP9XQKBgGww5dche4mpWK+UGWe7ys9jhtLp95UO7VnIrDbjglS4am4lU9N2\nUqaBLWggfUQzN7tMcCglWL0AaTGubrx1CrENhGeXRw+rrQBmgHeiomgDZlLcUWzd\nFY++DgTCRYgF3utI+DSSitaUas1AeEcZ+84WdlLOv+j5Py3ThrBdHSCpAoGBAI9c\nGp0c0pse198UarG7wxsfGpqZLqXi1i+YujvXNHAsY7K5i73+SaB12MkooXpcU8OQ\nLPZG4QrF0CkQWObJQio4L2mwxZAZNBbXgN4Yn8EpSLWRV8535uFJX4PaAzinmBRm\n0l7qSbUPKTulD1zUZH8tZd52HJxf8dO7Y0eLwiAZAoGBAIbm30GfZP6bXt1/JjMZ\nppSujPmwI1ofx1niNHtWpBgNXhyRLYoDlnCVJJjUAREF7DLZ3/+vxZ8c5F4iSbGo\n0MZ0l6Tf7d1W54r9MCPPx/eCC3jvAevibS/3SVZgALnT3LjpOLhSW34zBOf/g7Ek\nHY7hYLMgYiC22AhHe3SQDYZE\n-----END PRIVATE KEY-----\n",
client_email = "unicornfinderbot@gen-lang-client-0982832571.iam.gserviceaccount.com",
client_id = "117871519318503085808",
auth_uri = "https://accounts.google.com/o/oauth2/auth",
token_uri = "https://oauth2.googleapis.com/token",
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs",
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/unicornfinderbot%40gen-lang-client-0982832571.iam.gserviceaccount.com",
universe_domain = "googleapis.com"



# 2. 이메일 설정 (이번에 새로 추가하는 것!)
[smtp]
email_address = "unicornfinder0328@gmail.com"
app_password = "kqye rmol wdul oirx"
